### ISSUE TITLE
validate_oauth2_token permission missed 

### ISSUE THREAD

**Issue by AlvaroVega** [ging/keystone-oauth2-extension#1]
In order to install oath2-extension, I guess the rollowing permission should be added to /etc/keystone/policy.json

```
 "identity:validate_oauth2_token": "", 
```

**Comment by garcianavalon** [comment]
True, there are some new permissions to add in etc/policy.json. We have the full list of them but forgot to add them to the repo.

**Comment by AlvaroVega** [comment]
And probably: 

```
   "identity:request_authorization_code"
   "identity:create_authorization_code"
   "identity:list_authorization_codes"
```

**Comment by federicofdez** [comment]
Hi,
We have just pushed a `policy.json` file (inside the `config` folder) which contains the policies that need to be defined. Thank you for your report.
Regarding the `identity:validate_oauth2_token` policy, we checked it and it looks like that it does not need to be defined, since token validation is actually made through `get_access_token`.

**Comment by AlvaroVega** [comment]
Thanks, we can close this issue

**Comment by federicofdez** [comment]
Thank you, I'm closing it then.
