### ISSUE TITLE
How to make use of the external OAuth2 provider via this extension

### ISSUE THREAD

**Issue by intellinfra-dev** [ging/keystone-oauth2-extension#10]
Given that I have an external OAuth2 service provider, I'd like to make use of it in Keystone. Following your guide, I can setup this extension in keystone, but I still have no idea of how to make keystone aware of the external OAuth2? Is there any guide on the step-by-step configuration? Thanks a lot.

**Comment by federicofdez** [comment]
Hello @li-ma ,

I'm afraid that we aren't currently supporting this extension, so sorry for the wrong delay in giving you a reply. Just in case you still find it useful:

We provide an installation step-by-step guide in our [readme](https://github.com/ging/keystone-oauth2-extension#how-to-install). Basically, once the extension is inside your Keystone project, you need to do the following:
1. Since this extension is augmenting a pipeline (see [Keystone docs](http://docs.openstack.org/developer/keystone/extension_development.html#modifying-the-keystone-paste-ini-file) for more info), a corresponding `filter:` section is necessary to be introduced in your `etc/keystone-paste.ini` file. Just place the following:
   `
   [filter:oauth2_extension]
   paste.filter_factory = keystone.contrib.oauth2.routers:OAuth2Extension.factory
   ` 
2. In order for the extension to work, it must be placed in the `pipeline`.
3. Edit the `[auth]` section in your `keystone.conf` file (the one placed in the `etc` folder in your Keystone project), to include OAuth 2.0 auth method, just like this:
   
   <pre>
   # Default auth methods. (list value)
   methods=external,password,token,<b>oauth2</b>
   </pre>
   
   At the end of the section you have to add this:
   
   ```
   # The oauth2 plugin module (string value)
   oauth2=keystone.auth.plugins.oauth2.OAuth2
   ```
4. Finally, you need to define new policies in your `policy.json` file (the one placed in the `etc` folder in your Keystone project) for the following targets: 
   
   ```
   identity:list_authorization_codes
   identity:revoke_access_token
   identity:request_authorization_code
   ```
   
   The file `config/policy.json` contains default values you can use, as well as other required policies which Keystone should include by default.

**Please note that we are currently not supporting this extension, hence I must warn you that it might not work as expected.**

Thank you for writing. Let me know if we can still be of any further help.

Regards,
Federico
